language: node_js
sudo: false
node_js:
- '5.4.1'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@3.5.3
install:
  - npm install